### ISSUE TITLE
[BUG] Deploy to TakeShape button is broken

### ISSUE THREAD

**Issue by lelouchB** [takeshape/README#3]
## Describe the bug
@incompl 

When clicking the **Deploy to TakeShape** button it redirects to 

https://app.takeshape.io/add-to-takeshape?repo=https://github.com/takeshape/TwitHub/tree/master/.takeshape/pattern

![image](https://user-images.githubusercontent.com/45850882/98252768-4e129080-1fa0-11eb-8a0e-fd23994a3045.png)

which results in an error since the repo has only one branch named **trunk**.

![image](https://user-images.githubusercontent.com/45850882/98253128-a9dd1980-1fa0-11eb-87ac-ebfdcebaec9c.png)

## To Reproduce

Click on the **Deploy to TakeShape** button.
You should face the following error.

![image](https://user-images.githubusercontent.com/45850882/98253197-bd888000-1fa0-11eb-880d-7f29d33d0661.png)

I faced this issue and wanted to fix it but I guess it can be only done by updating **master** with **trunk** on TakeShape.

**Comment by incompl** [comment]
Fixed, thanks!
